- build/releng/com.liferay.ide-repository/bundle/bundle.properties
Hi Greg,
I've made a new commit for this instead of cherry-pick the one on master since the file location has been changed.
Please let me know if there is anything need to be updated.
> IDE-2041 update eclipse bundles to mars R

- tools/features/com.liferay.ide.hidden/feature.xml
> add blade migrate api to build

- build/com.liferay.ide-repository/bundle/build.xml
- build/com.liferay.ide-repository/bundle/bundle.properties
I've tried according your changes, it could build all the bundles successfully now. Thanks.
> create mac bundle for ide30 m1

- tools/tests/com.liferay.ide.project.core.tests/src/com/liferay/ide/project/core/tests/modules/BladeCLITests.java
there is a new template toady: contenttargetingrule. Change the template length to make liferay-ide run ok.
> Update templates length in blade junit test

- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/AbstractCanvas.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/GearControl.java
Hey Greg, I tested this commit on linux , and works well , you can test it on your mac and see if it resolves the number visiability problem.
> IDE-2901 use our own time to avoid gear breaking

- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/AbstractLiferayTableViewCustomPart.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/CustomJspPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/DescriptorsPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/InitConfigureProjectPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/LayoutTemplatePage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/LiferayDescriptorUpgradeTableViewCustomPart.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/LiferayLayouttplUpgradeTableViewCustomPart.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/LiferayUpgradeDataModel.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/NavigatorControl.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/Page.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/UpgradeView.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/WelcomePage.java
> IDE-2900 code upgrade UI improve

- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/BuildServicePage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/FindBreakingChangesPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/WelcomePage.java
improve descriptions in liferay code upgrade pages
> IDE-2915 improve descriptions in liferay code upgrade pages

- tools/plugins/com.liferay.ide.gradle.core/src/com/liferay/ide/gradle/core/LiferayWorkspaceProjectProvider.java
as the liferay-workspace version will change and it is hard to follow the default bundle url value , we just write the current bundle url to gradle.properties and run initBundle task
> fix bundle url default value

- tools/tests/com.liferay.ide.project.core.tests/src/com/liferay/ide/project/core/tests/modules/NewLiferayModuleProjectOpTests.java
> IDE-2962 Can't add property while the template is portlet-provider

- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/SummaryPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/UpgradeView.java
when you click the page title in the summary page, it will jump to corresponding page
> IDE-3003 add the second page and click event to summary page

- maven/plugins/com.liferay.ide.maven.core/src/com/liferay/ide/maven/core/MavenBundlePluginProject.java
- tools/plugins/com.liferay.ide.gradle.core/src/com/liferay/ide/gradle/core/LiferayGradleProject.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/util/ProjectUtil.java
- tools/plugins/com.liferay.ide.server.core/src/com/liferay/ide/server/core/portal/BundlePublishFullRemove.java
if you deploy a maven or gradle project  in ide and delete output file in filesystem and undeploy the module in ide and it will show some NPE error.
and this is just a bug fixing and I think no need to add junit test.
> get bsn from bnd.bnd firstly and fix NPE

- maven/plugins/com.liferay.ide.maven.core/src/com/liferay/ide/maven/core/pref/MavenArchetypePreferenceInitializer.java
hey @gamerson can you merge it firstly as It causes some bugs as the old template using old bundle.support lib, I will ask @JoyeLuo work on the Maven support soon. thanks
> IDE-3595 update liferay maven workspace version to latest

- build/parent/pom.xml
> update tag to '-ga1'

- maven/plugins/com.liferay.ide.maven.core/src/com/liferay/ide/maven/core/LiferayMavenWorkspaceProjectProvider.java
- maven/plugins/com.liferay.ide.maven.core/src/com/liferay/ide/maven/core/MavenProjectBuilder.java
- tools/plugins/com.liferay.ide.gradle.core/src/com/liferay/ide/gradle/core/GradleProjectBuilder.java
- tools/plugins/com.liferay.ide.gradle.core/src/com/liferay/ide/gradle/core/LiferayGradleWorkspaceProjectProvider.java
- tools/plugins/com.liferay.ide.project.core/META-INF/MANIFEST.MF
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/IWorkspaceProjectBuilder.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/jobs/InitBundleJob.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/jobs/JobUtil.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/util/LiferayWorkspaceUtil.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/workspace/NewLiferayWorkspaceProjectProvider.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/InitConfigureProjectPage.java
we create the job class for initBundle task to share with the classes which need to init bundle like creating liferay workspace or code upgrade tool
> Init bundle job

- tools/plugins/com.liferay.ide.gradle.core/src/com/liferay/ide/gradle/core/GradleUtil.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/jobs/InitBundleJob.java
- tools/plugins/com.liferay.ide.project.core/src/com/liferay/ide/project/core/workspace/NewLiferayWorkspaceProjectProvider.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/InitConfigureProjectPage.java
- tools/plugins/com.liferay.ide.project.ui/src/com/liferay/ide/project/ui/upgrade/animated/Page.java
hey @gamerson, I'd like to put the changes into the next release. it is a great improvement that doesn't make the code upgrade tool freeze during importing projects, init bundle and so on.
> IDE-4152 make code upgrade tool process work asynchronously

- build/parent/pom.xml
> Fix broken p2 repo

- functional-tests/common/com.liferay.ide.functional.liferay/src/com/liferay/ide/functional/liferay/support/server/PureTomcat72Support.java
- functional-tests/tools/modules.ext/modules.ext.files.wizard/modules.ext.files.wizard.validation/src/com/liferay/ide/functional/modules/ext/files/wizard/tests/ValidationModulesExtFilesTests.java
- functional-tests/tools/workspace/workspace.wizard/workspace.wizard.validation.tomcat.70/src/com/liferay/ide/functional/workspace/tests/ValidationLiferayWorkspaceTests.java
- tests-resources/bundles.csv
- tools/plugins/com.liferay.ide.core/src/com/liferay/ide/core/util/WorkspaceConstants.java
These are the changes on IDE side, already sent another pr to your liferay-portal repo here: gamerson/liferay-portal#367
> Ide 4701 update bundle url and target platform from 7.2.0 to latest 7.2.1

- build/installers/liferay-workspace/liferay-workspace.xml
> add 7.3 option in worksapce installer

- build/installers/liferay-workspace-with-devstudio/liferay-workspace-with-devstudio.xml
- build/installers/liferay-workspace/liferay-workspace.xml
1. ce: portal-7.3-ga6
2. dxp: dxp-7.3-ga1
> IDE-4894 update installers to liferay 7.3

- functional-tests/base/module.deploy.base/src/com/liferay/ide/functional/module/deploy/base/DeployModuleLiferayWorkspaceGradleTomcat7xBase.java
- functional-tests/base/server.deploy.base/src/com/liferay/ide/functional/server/deploy/base/Wildfly7xDeployBase.java
- functional-tests/common/com.liferay.ide.functional.liferay/src/com/liferay/ide/functional/liferay/action/EditorAction.java
- functional-tests/common/com.liferay.ide.functional.liferay/src/com/liferay/ide/functional/liferay/page/editor/ServerEditor.java
- functional-tests/common/com.liferay.ide.functional.swtbot/src/com/liferay/ide/functional/swtbot/UI.java
- functional-tests/tools/module/module.deploy/module.deploy.tomcat.70/src/com/liferay/ide/functional/module/tests/DeployModuleLiferayWorkspaceGradleTomcat70Tests.java
- functional-tests/tools/module/module.deploy/module.deploy.tomcat.71/src/com/liferay/ide/functional/module/tests/DeployModuleLiferayWorkspaceGradleTomcat71Tests.java
- functional-tests/tools/server/server.settings/server.settings.tomcat.72/src/com/liferay/ide/functional/server/tests/ServerEditorTest.java
- functional-tests/tools/server/server.settings/server.settings.tomcat.72/src/com/liferay/ide/functional/server/tests/ServerEditorTests.java
- source-formatter.properties
Hi @gamerson , here are some functional tests updates.
But our servers in the office are down now, and the china office won't open next week.  I will open our servers as soon as the office open. 
So we won't have functional and integration tests pr in every pull requests for the time being.
> Functional test
